export enum ECMSContent {
	AGENT = "agents",
	BLOG = "blogs",
	COMPANY = "companies",
	CUSTOMER_CONTACT_REQUEST = "customer-contact-requests",
	CUSTOMER_PAST_EXPERIENCE = "customer-past-experiences",
	DEAL_TYPE = "deal-types",
	DEVELOPER = "developers",
	FAQ = "faqs",
	PROPERTY = "properties",
	PROPERTY_AMENITY = "property-amenities",
	PROPERTY_CATEGORY = "property-categories",
	CITY = "cities",
	ABOUT = "about",
	COMPANY_OFFICE = "company-offices",
	PROJECT = "projects",
	UPLOAD = "upload",
	DISTRICT = "districts",
	HEATING_TYPE = "heating-types",
	PARKING_TYPE = "parking-types",
	PROPERTY_CONDINTION_TYPE = "property-condintion-types",
	PROPERTY_STATUS_TYPE = "property-status-types",

}
