export * from "./IResponse";
export * from "./IAgent";
export * from "./IGetContentParams";
export * from "./IGetContentResponse";
export * from "./IProperty";
export * from "./IBlog";
export * from "./ICompany";
export * from "./ICreateContentParams";
export * from "./ICustomerContactRequest"